### PR TITLE
Bump systems to nerves_system_br 1.29.1 versions

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
@lawik The review is more to let you know about the update than anything else. If you wanted to try out an example on whatever hardware is most convenient to you, that would be great, but not necessary.

**Comment by fhunleth** [comment]
Btw, I just noticed that I forgot to update the Erlang and Elixir version in the README.md to correspond to what's in the `.tool-versions` and CI. That's fixed.

**Comment by lawik** [comment]
I just put hello_live_view on an rpi4 and apparently I can't get to the Phoenix app.
It built fine. I think I have mDNS problems or something. I ssh to the nerves-XYZ...A.local hostname fine but not `hello_live_view.local`.

Builds fine though.

**Comment by fhunleth** [comment]
Thanks. The mDNS issue doesn't sound system related.

**Pull request merged**
