### PR TITLE
Adds example of combined Nerves and Phoenix/LiveView in one application

### PR DESCRIPTION
**Pull request by pkinney**
This adds a `hello_live_view` example that integrates Phoenix/LiveView and Nerves into the same application, in contrast to the umbrella project or poncho project approach.

I called it `hello_live_view` to follow the apparent naming convention, but I'm not sure if that distinguishes this from the current `hello_phoenix` poncho project example.  If there is a better name, let me know and I can update it.

I tried to keep things mostly unopinionated, but I did install TailwindCSS as a way to give someone a starting point for building a web app right away.  I'm open to removing this if it's too distracting from the example.

### CODE REVIEW

**Comment by fhunleth** [comment]
@pkinney Thank you for submitting this! We definitely need a combined Phoenix/Nerves example, so this is super helpful. I'll defer to @jjcarstens for reviewing, but I'm 👍 for merging.

**Comment by jjcarstens** [comment]
🎉 LGTM - I agree on the naming, but don't know if I have a better idea. Maybe we rename these to `hello_phoenix_poncho` and `hello_phoenix_single_app`? Or maybe just the latter since I don't know how many references to `hello_phoenix` are floating around

**Comment by fhunleth** [comment]
Sounds good. I'll merge and then we can iterate as we get ideas on naming changes, etc.

@pkinney Thanks!!

**Comment by pkinney** [comment]
Happy to!

I'd also be happy to take care of the renaming of the two projects if the naming is settled on.

**Pull request merged**
