### PR TITLE
create a basic "hello zig" application

### PR DESCRIPTION
**Pull request by ityonemo**

### CODE REVIEW

**Comment by fhunleth** [comment]
Nice!! I'm looking forward to trying this out!

**Comment by fhunleth** [comment]
@ityonemo I tried it out this morning! This is really cool.

I made a few changes and pushed them to https://github.com/nerves-project/nerves_examples/compare/ityonemo-master.

I've timed out for today, but I think what's left is to either get CI passing or to not run CI on some Nerves systems. I'd prefer to get `hello_zig` running on all Nerves systems, but I'm not sure how much work that is. 

Not all of them have been built, but I can see that the `nerves_system_x86_64` build is breaking:

https://circleci.com/gh/nerves-project/nerves_examples/9094?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

All CI results are here for you to take a look in case there are others: https://circleci.com/gh/nerves-project/nerves_examples/tree/ityonemo-master.

**Comment by fhunleth** [comment]
CI completed. x86_64 was the only one that didn't compile. Also, I did try a Raspberry Pi Zero this morning and it didn't work. I haven't debugged that yet.

**Comment by ityonemo** [comment]
is this x86_64 an embedded x86_64 platform?  I might have written code that assumes that "if it's not host, default to arm".

**Comment by fhunleth** [comment]
Yes, it's this: https://github.com/nerves-project/nerves_system_x86_64/. This one uses musl libc

There are unofficial Nerves systems for 32-bit and 64-bit x86 systems. There are also unofficial aarch/ARM 64 platforms out there and MIPS ones have popped up every once in a while. 

It seems like Nerves might need to supply the target triple to Zigler. Usually we set environment variables with things like this since there's no direct path from where the knowledge exists (Nerves System) to where the tools get called (elixir_make, etc.)

**Comment by ityonemo** [comment]
for now, I should be able to just hard code the target and musl libc abi, this is quite literally the entirety of my nerves detection code https://github.com/ityonemo/zigler/blob/24c49dc3fedf5cf83c0257736b02483f490f3e44/lib/zigler/zig.ex#L79-L93 😅.  I'll try to push it tonight.

**Comment by fhunleth** [comment]
Ahh. I see how it works. Thanks for the link.

Would you mind changing it to not use mix targets? Except for `host`, mix targets are user-chosen, so they're not that reliable.

Right now, I'm thinking that if the mix target is not the host that you can find out what to do via `-dumpmachine`. Nerves sets `$CC` so you can do something like this:

```sh
$ $CC - -dumpmachine
x86_64-unknown-linux-musl
```

Currently Nerves officially supplies toolchains that will print the following:

```text
aarch64-unknown-linux-gnu
arm-unknown-linux-gnueabihf
armv5tejl-unknown-linux-musleabi
armv6-rpi-linux-gnueabi
i586-unknown-linux-gnu
mipsel-unknown-linux-musl
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl
```

Of these, `arm-unknown-linux-gnueabihf`, `armv6-rpi-linux-gnueabi`, `x86_64-unknown-linux-gnu`, and `x86_64-unknown-linux-musl` are the most used ones for Nerves in OSS projects. Nerves examples would exercise all but the x86/gnu one.

**Comment by ityonemo** [comment]
I like this solution (what I have is definitely super-hacky) much better and I think that zig respects those machine strings verbatim.  I'll bet there's a good chance this will clear up the rpi0 issue as well.

**Comment by fhunleth** [comment]
I dug into the rpi0 issue a little more. I think that `-target arm-linux-gnueabi -mcpu arm1176jzf_s` is the right thing to pass to restrict the opcodes to ones that work on ARMv6.

Looking at https://github.com/ziglang/zig/blob/master/src/target.cpp, I don't see a way to indicate the CPU as part of the `-target`. It looks like `-mcpu` is required. 

I'd expect the same issue to apply to `armv5tejl`. For Nerves, the generic "arm" crosscompiler targets a Cortex-A8 (ARM v7 architecture). Whatever the zig default is, it has to be close to this since it seems to work.

**Comment by fhunleth** [comment]
Rebased, updated, etc. in #184. Should be merged soon!!!!

**Pull request closed without merging**
