### PR TITLE
Switch examples to nerves_pack and vintage_net

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
This updates all of the examples to use `nerves_pack` using the new `nerves_bootstrap`. I haven't run any of these on real hardware yet. If anyone is around to try these out, please post if you test anything since I'll test others when I next get a chance.

**Comment by fhunleth** [comment]
Blinky works on RPi0.

**Comment by GregMefford** [comment]
Testing `hello_network` on `rpi0`, I'm able to SSH into the device via gadget Ethernet or WiFi (after adding the required configuration for WiFi). There's an issue where the current application code demonstrates some run-time configuration of `Nerves.Network`, which obviously won't work with `VintageNet`. I'm not sure how we want to proceed with that - should this example show to do reconfigure `VintageNet` at runtime, or perhaps just show how to pre-configure wired/WiFi/Gadget interfaces all in the `config.exs` and seamlessly connect to any of them depending on what interfaces are available in the hardware?

```
Application hello_network exited: HelloNetwork.start(:normal, []) returned an error: an exception was raised:
    ** (UndefinedFunctionError) function Nerves.Network.setup/1 is undefined (module Nerves.Network is not available)
        Nerves.Network.setup("eth0")
        (hello_network) lib/hello_network.ex:40: HelloNetwork.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by fhunleth** [comment]
I just updated all of the `config.exs`/`target.exs` files based on updates to `nerves_bootstrap`.

@GregMefford I'm wondering if replacing `hello_network` with the `vintage_net_wizard` example makes sense. Supporting configuration by switching to AP mode seems like it would be a lot more interesting anyway.

**Comment by GregMefford** [comment]
@fhunleth Yeah that is a good idea! I was trying to think of what purpose `hello_network` was serving that isn't also covered by `hello_phoenix`, but I like the idea of having that example demonstrating how to use some `vintage_net` features, like `vintage_net_wizard`, so we can keep the Phoenix one focused on just the tweaks that make Phoenix work well on embedded devices.

**Comment by fhunleth** [comment]
FYI - I removed the `nerves_network` example, since it seems like it could only create confusion now with `vintage_net`. It's definitely a hole, though, in the list of examples that should be filled, but I don't think that's happening in this PR.

**Pull request merged**
