### PR TITLE
Adding Nerves Example for use as an SNMP Manager (Poller)

### PR DESCRIPTION
**Pull request by itwasscience**
This pull request adds a Nerves example for using a target device as an SNMP manager using the Erlang SNMP Manager application. It details some specifics around the Erlang SNMP configuration files that are not obvious as they need to be present in the filesystem.

The demonstration consists of polling two OIDs from a remote host with IP connectivity from the Nerves build target every 5 seconds, parsing the results and adding them to the RingLogger buffer.

The `sysDescr` and `sysName` OIDs should be available for most remote devices.

This has been tested on an Ubuntu Linux 20.04.2 machine as host with a build target of `rpi0` using the `rpi0w` hardware and my home router (Cisco 1841). Both the host and target are successfully polling the remote device.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thank you very much for submitting this! I tried it out and it worked first try. The instructions were very easy to follow.

My only critique is that everything has to be hardcoded in configuration files in the firmware image. It would be nice if the configuration could be applied at runtime so that IP addresses, user names, etc. could, in theory, be changed. It looks like there's a way to register agents dynamically so that might make it possible to get rid of agents.conf. 

If nothing comes out of this over the next couple days, I'm thinking of merging and then revising later if better ways are found.

**Comment by itwasscience** [comment]
Thank you, I'm glad to hear it! The Elixir wrappers themselves might be worthy of standalone hello applications (or replacing this one) which are definitely easier to manipulate at runtime. 

I'm not really sure where to even start on making the Erlang runtime configurations at runtime I've haven't done much with integrating outside of Elixir yet. I have a feeling it would wind up being like the existing Elixir packages but worse!

**Comment by fhunleth** [comment]
I looked around too and I agree with your assessment.

I'll finish merging some dependency and CI updates tonight and will rebase and merge your PR afterwards. Thanks!

**Comment by fhunleth** [comment]
Manually rebased and merged. Thanks again!

**Pull request closed without merging**
