### PR TITLE
initital distributed blinky

### PR DESCRIPTION
**Pull request by tverlaan**
I haven't been able to test this on actual raspberry pi's. Since I'm going on a trip this Friday I'm not sure if I'll be able to do that. If someone finds the time to test this it would be great. It works on my machine™

It is based on my other repo, but improved here and there. Both more clean and more complete (as in reproducability).

### CODE REVIEW

**Comment by GregMefford** [comment]
Thanks a bunch for this contribution! :+1:
I think this makes a great next-step for people after they try out `blinky` and `hello_network`.

I should be able to give it a try this weekend to confirm it works, if no one else gets to it first.

**Comment by GregMefford** [comment]
Oh, I also forgot to mention: don't worry about the CI failure message. This is a known issue with the `rpi` System, unrelated to your code.

**Comment by GregMefford** [comment]
I just wanted to leave a note to let you know that I didn't forget about this PR. I worked on it a little today, but ran into a few unrelated snags in getting my environment ready to test.

I'm hoping to make some time this week to test, make a few tweaks for consistency, and get this merged.

Thanks again! :balloon: :bowtie:

**Comment by ghitchens** [comment]
@GregMefford any update on this?  I don't have the setup to test it.

**Comment by GregMefford** [comment]
Sorry, no update yet other than I worked on it a bit a couple weeks ago, but then I got too busy to get back to it. I still plan on getting this merged soon, though.

**Comment by bendiken** [comment]
@GregMefford Note that the with the QEMU target now usable, that might make for the easiest set up to test multiple distributed Nerves instance.

**Comment by GregMefford** [comment]
@tverlaan I'm sorry for stalling this PR for so long!

I played with it tonight and made some tweaks to get the versions of dependencies up to date, but I'm not able to actually get it to work because of issues with the cookie file.

It's failing to boot up and saying `Cookie file /root/.erlang.cookie must be accessible by owner only`, which I think shouldn't happen when the Erlang process is started in distributed mode. I wasn't able to find anywhere in your code that is trying to start `epmd` dynamically, but does [this branch](https://github.com/nerves-project/nerves-examples/tree/tverlaan-distributed_blinky) work for you in its current state?

You may also want to take a look at the discussion on [Nerves PR 30](https://github.com/nerves-project/nerves/pull/30) about how we want to guide people to use Erlang Distribution. I think since this example uses static configuration, it's already consistent with that document, but wanted to make sure you're aware as we finish up the troubleshooting and get this merged.

**Pull request closed without merging**
