### PR TITLE
hello_scenic: Initial commit

### PR DESCRIPTION
**Pull request by ringlej**
image

### CODE REVIEW

**Review by jjcarstens — COMMENTED** [review]
Thanks @ringlej ! I triggered the pipeline for this to make sure it can build. Would you mind also adding the new example to the list in README.md as well? 🙏🏼

**Comment by fhunleth** [comment]
@jjcarstens This also requires Nerves system updates so it will take a bit to be mergeable. We discussed this but I forgot to update the status here. The summary is that we need to check libcairo support and do a sanity check across the official Nerves devices that support video outputs.

**Comment by fhunleth** [comment]
@ringlej I merged the two unrelated commits you had in this PR, squashed the other two you had, updated dependencies and rebased on main. 

I'm having good luck with trying it out, and Nerves systems updates with libcairo are almost released for Raspberry Pi and MangoPi. 

I think the main thing preventing merging this PR now is that `:scenic_driver_local` needs a release. Do you know if that can happen soon?

**Comment by ringlej** [comment]
> I think the main thing preventing merging this PR now is that `:scenic_driver_local` needs a release. Do you know if that can happen soon?

I don't have control over that.
@certel @axelson?

**Comment by axelson** [comment]
Yes that can happen soon. We're currently planning to cut a release by the end of the year!

**Comment by fhunleth** [comment]
@ringlej @axelson Do either of you have an update on `scenic_driver_local`?

**Comment by fhunleth** [comment]
I updated the `scenic_local_driver` to pull from GitHub rather than hex.pm.

**Comment by crertel** [comment]
Thanks @fhunleth . I'm trying to get a new RC cut this week/weekend.

**Comment by fhunleth** [comment]
@crertel That's great. Thank you!

**Pull request merged**
