### PR TITLE
Upgrade dependencies of hello_phoenix

### PR DESCRIPTION
**Pull request by mnishiguchi**
### Description

This example was created long time ago. Now that Phoenix 1.6 is released, it is time to upgrade dependencies and code for this example.

### Changes

- Re-generate Phoenix app (ui)
- Re-generate Nerves app (firmware)
- Remove deprecated UI config settings: `:root`, `:load_from_system_env `
- Implement minimal LiveView that shows at least something from the firmware

### Notes

- The UI did not work in `MIX_ENV=dev` presumably due to newly introduced `esbuild`. As a workaround, we can stop loading it at runtime when the target is not host.

### TODO

- [x] Do the changes in code
- [x] Does it work?
- [x] Update the instructions in Readme of this example
- [x] Update the [Nerves hex doc](https://hexdocs.pm/nerves/user-interfaces.html#phoenix-web-interfaces)

### CODE REVIEW

**Comment by mnishiguchi** [comment]
@fhunleth I was able to update the dependencies and code successfully. It is working well (code complete), but next I need to update the instructions. The steps for Phoenix 1.6 is a lot simpler!

I have one question. Does `upload.sh` need to be generate by the user? I thought it would be nice for the beginners if that is included in the project.

**Comment by fhunleth** [comment]
My wish would be that `mix upload` worked for everyone. But back to `upload.sh`, I never commit it. I do understand your point. I really wish that it were not needed.

**Comment by mnishiguchi** [comment]
One thing I am not sure about in the UI config is `load_from_system_env`. [Existing `hello_phoenix`](https://github.com/nerves-project/nerves_examples/blob/96e9b0d73f5c7fb38a56bd1650775f34f9cb0a60/hello_phoenix/firmware/config/target.exs#L3) does not have it specified, but [Nerves doc](https://hexdocs.pm/nerves/user-interfaces.html#configure-phoenix) implies it is needed. Maybe the doc is outdated? 🤔

**Comment by fhunleth** [comment]
Do you know if there was any other text before `** (Mix) Nerves encountered an error. %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}`? It would be nice to know what that error was and then fix it. Either that or provide more information.

**Comment by mnishiguchi** [comment]
Yeah I should have kept more error messages. I tried to re-create the issue now but had no luck. I'll get more info next I see that error.

**Comment by fhunleth** [comment]
@mnishiguchi I'm coming back to this one. I think this is good enough and we can update it in the future if we want to make it fancier. Could you take a quick look at it again and mark it as "ready for review" if you think it's ok?

**Comment by mnishiguchi** [comment]
✅  tested following the instructions in readme after rebasing on `main` branch

**Comment by fhunleth** [comment]
Nice. Thanks!

**Pull request merged**
